@extends('layouts.legal')

@section('title', 'Privacy Notice')

@section('content')
<article class="space-y-8">
    <header class="space-y-4 border-b border-white/10 pb-8">
        <p class="inline-block border border-amber-400/40 px-3 py-1 text-xs font-bold uppercase tracking-[0.16em] text-amber-300">Draft for legal review</p>
        <h1 class="text-4xl font-black sm:text-5xl">Privacy Notice</h1>
        <p class="text-gray-400">Draft date: September 29, 2026. This draft describes observed website features, but the Gym’s legal advisor and privacy lead must confirm the legal basis, retention schedule, disclosures, and final wording before publication.</p>
        <p class="text-gray-300"><strong>[Registered legal entity name]</strong> (“Infliction Gym,” “we,” or “us”) is the proposed personal information controller. Complete the operator, address, privacy contact, and effective date details in Section 10.</p>
    </header>

    <section class="space-y-3"><h2 class="text-2xl font-bold">1. Information this website handles</h2><ul class="list-disc space-y-2 pl-6 leading-7 text-gray-300"><li><strong>Account data:</strong> name, email address, password stored in hashed form, membership plan and status, FITPASS credit balance, and account timestamps.</li><li><strong>Support chat:</strong> messages and a browser-generated chat session identifier. Chat messages are stored by the website. The current chat feature may send a message and recent conversation context to Groq to generate a reply.</li><li><strong>Payment records:</strong> selected plan or credit quantity, amount, internal reference, PayMongo Checkout Session identifier, payment status, and webhook event identifier. The current application is designed not to store full card numbers or card security codes.</li><li><strong>Technical data:</strong> information needed for authentication, session handling, security, and service operation, including session and CSRF cookies. The chat session identifier is stored in browser local storage.</li><li><strong>Inquiry details:</strong> name, phone number, or email may be collected if you submit those details through a Gym inquiry channel. Confirm which channels are actually active and their retention behavior.</li></ul></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">2. Purposes</h2><p class="leading-7 text-gray-300">The proposed purposes are to create and manage accounts; provide member services; process and reconcile payments; respond to support requests; operate and secure the website; prevent fraud and misuse; maintain required records; and comply with legal obligations. Counsel or the privacy lead should map each purpose to an appropriate lawful basis under applicable Philippine privacy law.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">3. Service providers and disclosures</h2><p class="leading-7 text-gray-300">Data may be handled by service providers that support the site, including PayMongo for hosted checkout and payment confirmation, Groq for chat-response generation, and the Gym’s hosting, email, database, and security providers. Confirm the actual production vendors, contracts, data locations, and any cross-border processing before publication. We do not intend to sell personal information.</p><p class="leading-7 text-gray-300">Information may also be disclosed where required by law, to protect people or the service, or as part of a lawful business reorganization, subject to applicable safeguards.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">4. Payment information</h2><p class="leading-7 text-gray-300">When you proceed to checkout, PayMongo collects and processes payment details under its own terms and privacy notice. The Gym receives payment status and transaction references needed to provide the purchased service. Do not send payment-card details through support chat or email.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">5. Cookies and local storage</h2><p class="leading-7 text-gray-300">The website uses session and CSRF mechanisms needed for account and form security. The support chat stores a generated conversation identifier in local storage so a conversation can continue in the browser. Review whether analytics, advertising, or other non-essential storage is enabled in production; if so, disclose it and provide any consent choices required by law.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">6. Retention and security</h2><p class="leading-7 text-gray-300">We retain information only as long as reasonably necessary for the stated purposes, legal obligations, dispute handling, and legitimate business records. The Gym must set specific retention periods for inactive accounts, chat transcripts, inquiries, and payment records: <strong>[insert approved schedule]</strong>. We use reasonable administrative, technical, and organizational safeguards, but no internet transmission or storage system can be guaranteed completely secure.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">7. Your choices and rights</h2><p class="leading-7 text-gray-300">Subject to applicable law, you may ask to access or correct personal information, request deletion or restriction where available, object to certain processing, or raise a concern with the appropriate privacy regulator. You may clear the chat identifier through your browser’s site data controls. We may need to verify your identity and retain records where the law permits or requires it. Counsel should confirm the applicable rights, response periods, and complaint process.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">8. Children</h2><p class="leading-7 text-gray-300">The website and services are not intended to collect children’s information without the required parent or guardian involvement. The Gym should confirm its minimum member age, consent workflow, and handling of any information about minors before publication.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">9. Updates</h2><p class="leading-7 text-gray-300">We may update this notice when our practices or legal obligations change. The final notice should show its effective date and explain how material changes will be communicated.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">10. Privacy contact</h2><p class="leading-7 text-gray-300">Controller: <strong>[registered legal entity name]</strong><br>Address: <strong>[complete registered or operating address]</strong><br>Privacy officer/contact: <strong>[name or role and monitored email address]</strong><br>General contact: <a class="text-red-300 underline" href="mailto:InflictionGym@gmail.com">InflictionGym@gmail.com</a><br>Effective date: <strong>[date after legal approval]</strong></p></section>
</article>
@endsection