@extends('layouts.legal')

@section('title', 'Terms of Service')

@section('content')
<article class="space-y-8">
    <header class="space-y-4 border-b border-white/10 pb-8">
        <p class="inline-block border border-amber-400/40 px-3 py-1 text-xs font-bold uppercase tracking-[0.16em] text-amber-300">Draft for legal review</p>
        <h1 class="text-4xl font-black sm:text-5xl">Terms of Service</h1>
        <p class="text-gray-400">Draft date: September 29, 2026. Do not publish or rely on this draft until your legal advisor has reviewed and completed the bracketed items.</p>
        <p class="text-gray-300">These proposed terms apply to the Infliction Gym website and services in Magalang, Pampanga. Replace <strong>[registered legal entity name]</strong> with the correct operator and confirm the contact and business details below.</p>
    </header>

    <section class="space-y-3"><h2 class="text-2xl font-bold">1. Agreement and eligibility</h2><p class="leading-7 text-gray-300">By creating an account, purchasing a membership or FITPASS credit, or using gym facilities, you agree to the final terms presented by <strong>[registered legal entity name]</strong> (the “Gym”). If you do not agree, do not purchase or use the services. Members must meet the minimum age set by the Gym. A parent or legal guardian must review and accept the applicable terms for any member under 18, subject to legal review.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">2. Accounts and website use</h2><p class="leading-7 text-gray-300">Keep account information accurate and protect your sign-in credentials. You are responsible for activity performed through your account unless applicable law requires otherwise. Do not misuse the website, attempt unauthorized access, interfere with its operation, or submit unlawful or harmful content. The Gym may restrict website access where reasonably necessary to protect the service or its users.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">3. Membership plans and payment</h2><p class="leading-7 text-gray-300">The website currently displays Base Membership at PHP 2,650 per month, Premium Membership at PHP 2,800 per month, and FITPASS at PHP 483 per credit. Confirm before publication whether these amounts include applicable taxes and what services, access hours, coaching, and benefits each plan includes. The final amount and payment method must be shown before you authorize a payment.</p><p class="leading-7 text-gray-300">Online checkout is processed by PayMongo. The Gym does not receive or store your full card number or security code. A payment is not confirmed merely because you return to this website; membership or credits are applied after the payment provider confirms the transaction. Keep your receipt and transaction reference.</p><p class="border-l-2 border-red-500 pl-4 leading-7 text-gray-300"><strong>Important implementation note for counsel:</strong> the current integration creates a one-time checkout charge. It does not automatically renew or charge future months. Confirm and state the membership term, the exact access start and end dates, renewal process, and any future recurring-billing terms before publication. Do not describe a plan as automatically renewing unless that feature is implemented and separately disclosed and accepted.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">4. FITPASS credits</h2><p class="leading-7 text-gray-300">FITPASS credits are intended for the eligible access or service described by the Gym. Before publication, specify how a credit is redeemed, whether unused credits expire, whether credits are transferable, and what happens to credits when an account is suspended or closed. Do not promise a particular validity period until the Gym has adopted and implemented it.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">5. Cancellations, refunds, and billing questions</h2><p class="leading-7 text-gray-300">Proposed cancellation, pause, refund, failed-payment, duplicate-payment, and charge-dispute procedures: <strong>[insert the Gym’s approved policy, notice method, deadlines, and processing times]</strong>. Any policy must comply with applicable consumer-protection laws and must not remove rights that cannot legally be waived. For a payment question, contact InflictionGym@gmail.com and include the transaction reference; do not send complete payment-card details by email.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">6. Health, safety, and conduct</h2><p class="leading-7 text-gray-300">Use equipment and facilities responsibly, follow posted instructions, and promptly tell Gym staff about unsafe conditions or an injury. Exercise involves physical activity and may carry a risk of injury. Seek advice from a qualified health professional about whether an activity is appropriate for you. The Gym must provide any required health screening, emergency procedures, and separate waiver or informed-consent documents; this section is not a substitute for those documents.</p><p class="leading-7 text-gray-300">The Gym may suspend access for unsafe, abusive, unlawful, or seriously disruptive conduct, subject to applicable law and a fair process appropriate to the circumstances. Counsel should review any member suspension, property, injury, and liability provisions before use.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">7. Availability and third-party services</h2><p class="leading-7 text-gray-300">Class schedules, coaches, equipment, and website features may change or be temporarily unavailable. PayMongo and other third-party services are governed by their own terms and privacy notices. The Gym is not responsible for third-party systems to the extent permitted by law, but this does not limit any rights you have under applicable law.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">8. Privacy</h2><p class="leading-7 text-gray-300">The proposed Privacy Notice explains how the website handles account information, support chat messages, and payment records. Review it at <a class="text-red-300 underline" href="{{ route('legal.privacy') }}">Privacy Notice</a>. The Gym should identify its legal operator, privacy contact, purposes, retention periods, and service providers before publication.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">9. Intellectual property</h2><p class="leading-7 text-gray-300">Unless identified otherwise, website text, branding, and materials are owned by or licensed to the Gym. You may use the website for personal, lawful purposes. Do not copy or commercially use protected materials without permission. Third-party names, photographs, and services remain subject to their respective rights and licenses.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">10. Changes and termination</h2><p class="leading-7 text-gray-300">The Gym may update these terms prospectively by publishing a revised version and its effective date. Material changes to price, service, or renewal terms should be communicated and accepted as required by law. Account or facility access may be ended for a lawful reason, with any required notice, refund, or appeal process. Accrued rights and obligations remain subject to applicable law.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">11. Liability and governing law</h2><p class="leading-7 text-gray-300">Nothing in these terms excludes a consumer right or liability that cannot legally be excluded. Any limitation of liability, indemnity, dispute process, governing-law clause, or court venue must be drafted or approved by counsel for Philippine law and the Gym’s circumstances. Proposed governing law and venue: <strong>[legal advisor to complete]</strong>.</p></section>

    <section class="space-y-3"><h2 class="text-2xl font-bold">12. Contact and business details</h2><p class="leading-7 text-gray-300">Gym: Infliction Gym, Magalang, Pampanga<br>Operator: <strong>[registered legal entity name]</strong><br>Business address: <strong>[complete registered or operating address]</strong><br>Email: <a class="text-red-300 underline" href="mailto:InflictionGym@gmail.com">InflictionGym@gmail.com</a><br>Effective date: <strong>[date after legal approval]</strong></p></section>
</article>
@endsection